update just new recipe to include task type

diff --git a/src/improvements/justfile b/src/improvements/justfile
--- a/src/improvements/justfile
+++ b/src/improvements/justfile
@@ -1,6 +1,6 @@
 # Create a new template or task
 # e.g. just new [template|task]
-new COMMAND="":
+new COMMAND="" TASK_TYPE="":
     #!/usr/bin/env bash
     set -euo pipefail
     
@@ -16,6 +16,16 @@ new COMMAND="":
         echo "  • task      - Create a new task"
         echo
     }
+
+    show_task_types() {
+        echo
+        echo "Available task types:"
+        echo "  • l2 - L2Base task type, these tasks require a superchain address registry and can iterate over multiple l2chains"
+        echo "    eg: https://github.com/ethereum-optimism/superchain-ops/blob/main/test/tasks/mock/template/GasConfigTemplate.sol"
+        echo "  • simple - SimpleBase task type, these tasks require simple key value registry and are independent of the l2chains"
+        echo "    eg: https://github.com/ethereum-optimism/superchain-ops/blob/main/src/improvements/template/FinanceTemplate.sol"
+        echo
+    }
     
     # shellcheck disable=SC2050
     if [ "{{COMMAND}}" = "" ]; then
@@ -23,11 +33,31 @@ new COMMAND="":
         show_usage
         exit 1
     fi
-    
+
+    if [ "{{TASK_TYPE}}" = "" ]; then
+        echo -e "\n\033[31mError: No task type specified\033[0m"
+        show_task_types
+        exit 1
+    fi
+
+    case "{{TASK_TYPE}}" in
+        l2)
+            TASK_TYPE="L2TaskBase"
+            ;;
+        simple)
+            TASK_TYPE="SimpleBase"
+            ;;
+        *)
+            echo -e "\n\033[31mError: Invalid task type '{{TASK_TYPE}}'\033[0m"
+            show_task_types
+            exit 1
+            ;;
+    esac
+
     # shellcheck disable=SC2194
     case "{{COMMAND}}" in
         template)
-            ./script/create-template.sh
+            ./script/create-template.sh $TASK_TYPE
             ;;
         task)    
             ./script/create-task.sh
